Add IP entity
bieniu/ha-shellies-discovery pull request #105
Opened 2020-12-14 17:39 UTC by thomasgermain

see #104

I tested with shelly 1, shelly 2.5 and shelly dimmer 2.

I added the IP entity everywhere the `rssi` is.

2020-12-14 20:09 UTC, bieniu requested changes

2020-12-14 20:09 UTC, bieniu commented on python_scripts/shellies_discovery.py
> +    sensors_tpls = [TPL_TEMPERATURE, TPL_RSSI, TPL_SSID, TPL_UPTIME, None]
```suggestion
    sensors_tpls = [TPL_TEMPERATURE, TPL_RSSI, TPL_SSID, TPL_UPTIME, TPL_IP]
```

2020-12-14 20:09 UTC, bieniu commented on python_scripts/shellies_discovery.py
> +    sensors_tpls = [TPL_RSSI, TPL_SSID, TPL_UPTIME, None]
```suggestion
    sensors_tpls = [TPL_RSSI, TPL_SSID, TPL_UPTIME, TPL_IP]
```

2020-12-14 20:11 UTC, bieniu commented
Please format the code with `Black`.

2020-12-15 20:23 UTC, thomasgermain commented
it should be fine now 😃

2020-12-16 07:40 UTC, bieniu approved these changes

2020-12-16 07:40 UTC, bieniu commented
Good job, thanks 👍

2020-12-16 07:40 UTC, merged