Add support for Shelly Duo RGBW light bulbs
bieniu/ha-shellies-discovery pull request #585
Opened 2024-07-23 20:01 UTC by Xinayder

This PR adds support for Shelly Duo RGBW light bulbs. Currently only tested with a GU10.

`KEY_EFFECT_TEMPLATE` was added for Lovelace to properly display what effect is currently selected. I used the Shelly RGBW2 as a base, but had to change `KEY_BRIGHTNESS_VALUE_TEMPLATE` to `KEY_BRIGHTNESS_TEMPLATE` for the same reason previously described. The light bulb only supports 3 effects.

Thanks to @tc-maxx for providing a MQTT discovery payload for this light bulb (#424)

2024-08-03 09:06 UTC, bieniu requested changes
Please fix lint errors. My RGBW2 died so I need a while to get a new one to test this. Thanks!

2024-08-03 09:06 UTC, bieniu commented on python_scripts/shellies_discovery.py
> +            "red_template": "{%if value_json.mode == ^color^%}{{value_json.red}}{%else%}{{ none }}{%endif%}",
Please introduce `KEY_RED_TEMPLATE` constant with an abbreviation `r_tpl`.

2024-08-03 09:06 UTC, bieniu commented on python_scripts/shellies_discovery.py
> +            "green_template": "{%if value_json.mode == ^color^%}{{value_json.green}}{%else%}{{ none }}{%endif%}",
Please introduce `KEY_GREEN_TEMPLATE` constant with an abbreviation `g_tpl`.

2024-08-03 09:06 UTC, bieniu commented on python_scripts/shellies_discovery.py
> +            "blue_template": "{%if value_json.mode == ^color^%}{{value_json.blue}}{%else%}{{ none }}{%endif%}",
Please introduce `KEY_BLUE_TEMPLATE` constant with an abbreviation `b_tpl`.

2024-08-03 09:06 UTC, bieniu commented on python_scripts/shellies_discovery.py
> +            KEY_COMMAND_ON_TEMPLATE: f"{{^turn^:^on^{{%if red is defined and green is defined and blue is defined%}},^mode^:^color^,^red^:{{{{red}}}},^green^:{{{{green}}}},^blue^:{{{{blue}}}}{{%endif
Please remove unneeded spaces and `-`.

2024-08-03 09:06 UTC, bieniu commented on python_scripts/shellies_discovery.py
> +            KEY_BRIGHTNESS_COMMAND_TEMPLATE: "{^gain^:{{value|float|multiply(0.3922)|round(0)}}, ^brightness^:{{value|float|multiply(0.3922)|round(0)}}}",
```suggestion
            KEY_BRIGHTNESS_COMMAND_TEMPLATE: "{^gain^:{{value|float|multiply(0.3922)|round(0)}},^brightness^:{{value|float|multiply(0.3922)|round(0)}}}",
```

2024-10-04 17:18 UTC, tcsmaxx commented
Hi @Xinayder, it looks like there are still some requested changes for this PR. Would you be able to take a look and help implement the necessary adjustments? Let me know if there's anything I can assist with to move this forward. Thanks for your work on this!

2024-11-04 14:57 UTC, bieniu approved these changes

2024-11-04 14:58 UTC, merged

2024-11-04 15:04 UTC, Xinayder commented
My notifications were off for some reason, I am terribly sorry for forgetting about this PR. I'm happy that it was merged!

2024-11-04 15:06 UTC, bieniu commented
Thanks for your contribution 👍